---
name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup go
        uses: actions/setup-go@v1.0.2
        with:
          go-version: '1.13'
      - name: go vet/get/test/build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go vet *.go
          go get -v -d .
          go test -v -cover -race .
          go build -v -a .
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: snyk
        env:
          SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        run: |
          npm install --prefix="${HOME}" -g snyk
          "${HOME}/bin/snyk" auth "${SNYK_API_TOKEN}"
          "${HOME}/bin/snyk" test --file=go.mod
